BBCode = { SOI ~ content* ~ EOI }

content = { tag_block | escaped_bracket | text }

tag_block = {
    "[" ~ tag_name ~ tag_attr? ~ "]" ~ content* ~ "[/" ~ close_tag_name ~ "]"
}

tag_name = @{ (!("=" | "]" | "/" | " " | "\t" | "\n" | "\r") ~ ANY)+ }

close_tag_name = @{ (!("]" | " " | "\t" | "\n" | "\r") ~ ANY)+ }

tag_attr = @{ "=" ~ (!"]" ~ ANY)* }

escaped_bracket = @{ "\\" ~ "[" }

text = @{
    (!"[" ~ ANY)+
}
